In [97]:
# from google.colab import files

# uploaded = files.upload()

# for fn in uploaded.keys():
#   print('User uploaded file "{name}" with length {length} bytes'.format(
#       name=fn, length=len(uploaded[fn])))

In [136]:
import warnings
from sklearn.exceptions import UndefinedMetricWarning
from sklearn.metrics import classification_report, confusion_matrix

# Before calling metrics functions, suppress the warning
warnings.filterwarnings('ignore', category=UndefinedMetricWarning)

# Now you can call classification_report and confusion_matrix without seeing the warning
print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.68      1.00      0.81        13
           2       0.00      0.00      0.00         6

    accuracy                           0.80        30
   macro avg       0.56      0.67      0.60        30
weighted avg       0.66      0.80      0.72        30

[[11  0  0]
 [ 0 13  0]
 [ 0  6  0]]


In [137]:
import pandas as pd
import io


In [138]:
data=pd.read_csv(r'D:\archive\iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [139]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [140]:
dataset = pd.read_csv(r'D:\archive\iris.csv')
dataset

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [141]:
dataset=dataset.drop(columns=['Id'])

In [142]:
dataset.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [143]:
# X = dataset.drop(columns=['Species'])
# y = dataset['Species']

# from sklearn.preprocessing import LabelEncoder
# encoder =  LabelEncoder()
# y = encoder.fit_transform(y)
# Y = pd.get_dummies(y) 
one_hot_encoded_data = pd.get_dummies(dataset, columns = ['Species'],dtype=bool)
data = one_hot_encoded_data
X = one_hot_encoded_data.drop(columns=['Species_Iris-setosa', 'Species_Iris-versicolor',
       'Species_Iris-virginica'])
Y = one_hot_encoded_data[['Species_Iris-setosa', 'Species_Iris-versicolor',
       'Species_Iris-virginica']]

X_values=X.values
Y_values=Y.values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X_values,Y_values,test_size=0.2,random_state=0)

In [144]:
# print(df.columns)
# print(df.head())
r=Y.columns
r=np.array(r)

In [145]:
Y.value_counts()

Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
False                False                    True                      50
                     True                     False                     50
True                 False                    False                     50
Name: count, dtype: int64

In [146]:
X.shape

(150, 4)

In [147]:
Y.shape

(150, 3)

In [148]:
Y.shape

(150, 3)

In [149]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [150]:
Y

Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                   True                    False                   False
1                   True                    False                   False
2                   True                    False                   False
3                   True                    False                   False
4                   True                    False                   False
..                   ...                      ...                     ...
145                False                    False                    True
146                False                    False                    True
147                False                    False                    True
148                False                    False                    True
149                False                    False                    True

[150 rows x 3 columns]

In [151]:
# y1

In [152]:
Y

Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                   True                    False                   False
1                   True                    False                   False
2                   True                    False                   False
3                   True                    False                   False
4                   True                    False                   False
..                   ...                      ...                     ...
145                False                    False                    True
146                False                    False                    True
147                False                    False                    True
148                False                    False                    True
149                False                    False                    True

[150 rows x 3 columns]

In [153]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))




In [154]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [155]:
# Assuming y_train is one-hot encoded
y_train_labels = np.argmax(y_train, axis=1)

In [156]:
y_train_labels

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0], dtype=int64)

In [157]:
y_train_labels.shape

(120,)

In [158]:
from keras.utils import to_categorical

# Assuming y_train_labels is the original class labels (e.g., [0, 1, 2])
# Convert the class labels to one-hot encoded format
y_train_labels_one_hot = to_categorical(y_train_labels)

# Now, y_train_labels_one_hot will have shape (num_samples, num_classes)
# For example, if you have 3 classes and 10 samples, the shape will be (10, 3)


In [159]:
model.fit(X_train, y_train_labels_one_hot, batch_size=10, epochs=100)


Epoch 1/100
12/12 [==============================] - 0s 1ms/step - loss: 7.6257 - accuracy: 0.3250
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 7.1584 - accuracy: 0.3250
Epoch 3/100
12/12 [==============================] - 0s 1ms/step - loss: 6.7069 - accuracy: 0.3250
Epoch 4/100
12/12 [==============================] - 0s 1ms/step - loss: 6.2672 - accuracy: 0.3250
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 5.8619 - accuracy: 0.3250
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 5.4482 - accuracy: 0.3250
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 5.0929 - accuracy: 0.3250
Epoch 8/100
12/12 [==============================] - 0s 1ms/step - loss: 4.7242 - accuracy: 0.3250
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 4.3906 - accuracy: 0.3250
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 4.0899 - accuracy: 0.3250
Epoch 11/

In [160]:
# Obtain predicted class labels using your trained model and testing input features
y_pred = model.predict(X_test)
y_pred_class = np.argmax(y_pred, axis=1)  # Convert probabilities to class labels

# Define true class labels by extracting them from testing target variable
y_test_class = np.argmax(y_test, axis=1)  # If y_test is one-hot encoded


1/1 [==============================] - 0s 55ms/step


In [161]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))
# from sklearn.metrics import classification_report, confusion_matrix

# print(classification_report(y_test_class, y_pred_class))
# print(confusion_matrix(y_test_class, y_pred_class))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.00      0.00      0.00        13
           2       0.20      1.00      0.33         6

    accuracy                           0.20        30
   macro avg       0.07      0.33      0.11        30
weighted avg       0.04      0.20      0.07        30

[[ 0  0 11]
 [ 0  0 13]
 [ 0  0  6]]


In [162]:
(12+5+8)/30

0.8333333333333334

In [163]:
# Assuming your testing data is in the format (X_test, y_test)
# Where X_test contains the features and y_test contains the true labels

# Define y_test_labels by extracting true labels from y_test
y_test_labels = np.argmax(y_test, axis=1)  # If y_test is one-hot encoded


In [164]:
from keras.utils import to_categorical

# One-hot encode y_test_labels
y_test_one_hot = to_categorical(y_test_labels)


In [165]:
# Evaluate the model
model.evaluate(X_test, y_test_one_hot)


1/1 [==============================] - 0s 148ms/step - loss: 1.1271 - accuracy: 0.2000


[1.1271189451217651, 0.20000000298023224]

In [166]:
# Predict for the first 10 Observations
pred=model.predict(X_test[:10])
print(pred)

1/1 [==============================] - 0s 26ms/step
[[0.28013617 0.34472185 0.37514195]
 [0.30416033 0.31521225 0.38062745]
 [0.28013617 0.34472185 0.37514195]
 [0.3292254  0.28722227 0.3835523 ]
 [0.28013617 0.34472185 0.37514195]
 [0.28013617 0.34472185 0.37514195]
 [0.28013617 0.34472185 0.37514195]
 [0.28013617 0.34472185 0.37514195]
 [0.28013617 0.34472188 0.37514198]
 [0.28013617 0.34472188 0.37514198]]


In [167]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[2 2 2 2 2 2 2 2 2 2]
[[False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]]


In [168]:
# z = data.

In [169]:
# Prediction Result
for i in range(len(p)):
    print("Predicted-Class: {},   Name: {}".format(p[i], Y.columns[p[i]]))


Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
Predicted-Class: 2,   Name: Species_Iris-virginica
